/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 bubble_tea_and_cookies.gltf --transform 
Files: bubble_tea_and_cookies.gltf [5.05MB] > C:\Users\psree\Downloads\bubble_tea_and_cookies\bubble_tea_and_cookies-transformed.glb [633.33KB] (87%)
Author: Sm1yle (https://sketchfab.com/Sm1yle)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bubble-tea-and-cookies-db489df55b3648e89e824a9675706875
Title: Bubble Tea and Cookies
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/models/bubble_tea_and_cookies-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.PaletteMaterial001}
        position={[0.005, 0.185, 0]}
        scale={[0.778, 0.907, 0.778]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.PaletteMaterial002}
        position={[0, 1.937, 0]}
        scale={[1.021, 1.191, 1.021]}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials.PaletteMaterial003}
        position={[0.004, 1.75, -0.014]}
        rotation={[-3.111, 0.015, -3.031]}
        scale={[0.094, 2.059, 0.093]}
      />
      <mesh
        geometry={nodes.Object_58.geometry}
        material={materials["Material.006"]}
        position={[0.009, 0.992, 0.929]}
        rotation={[1.668, 0, -Math.PI]}
        scale={[-0.254, 0.145, 0.455]}
      />
      <mesh
        geometry={nodes.Object_62.geometry}
        material={materials.Material}
        position={[2.435, -0.786, -0.943]}
        scale={0.624}
      />
      <instancedMesh
        args={[nodes.Object_6_1.geometry, materials.PaletteMaterial003, 22]}
        instanceMatrix={nodes.Object_6_1.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Object_29.geometry, materials.lambert12, 8]}
        instanceMatrix={nodes.Object_29.instanceMatrix}
      />
    </group>
  );
}

useGLTF.preload("/models/bubble_tea_and_cookies-transformed.glb");
