/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 coffee_cup.gltf --transform 
Files: coffee_cup.gltf [21.96KB] > C:\Users\psree\Downloads\coffee_shop_cup\coffee_cup-transformed.glb [18.29KB] (17%)
Author: David Zerba (https://sketchfab.com/DavidZerba)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-shop-cup-37e6805f2b7a4158a1d61fe75f8e2a33
Title: Coffee Shop Cup
*/

import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/coffee_cup-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials.material}
        position={[0, 0.522, 0]}
        scale={0.233}
      />
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials.material_1}
        position={[0, 0.981, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.38, 0.357, 0.38]}
      />
      <mesh
        geometry={nodes.Object_9.geometry}
        material={materials.Sleeve}
        scale={0.233}
      />
    </group>
  );
}

useGLTF.preload("/models/coffee_cup-transformed.glb");
