/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 coffee_mug.gltf --transform 
Files: coffee_mug.gltf [4.05MB] > C:\Users\psree\Downloads\cafe_latte_with_art\coffee_mug-transformed.glb [310.8KB] (92%)
Author: horse_water (https://sketchfab.com/horse_water)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cafe-latte-with-art-9e73b558b8844e6f8e18c2aedcd05313
Title: Cafe Latte with Art (ラテアート)
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/coffee_mug-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Saucer_Cup_0.geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.453}
      />
      <mesh
        geometry={nodes.Latte_Latte_0.geometry}
        material={materials.Latte}
        position={[0, 0.49, 0]}
        rotation={[-Math.PI / 2, 0, 0.196]}
        scale={0.52}
      />
      <mesh
        geometry={nodes.Spoon_Metal_0.geometry}
        material={materials.Metal}
        position={[-0.253, 0.076, 0.352]}
        rotation={[-1.57, 0.018, 1.57]}
        scale={0.772}
      />
    </group>
  );
}

useGLTF.preload("/models/coffee_mug-transformed.glb");
