/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 desserts.gltf --transform 
Files: desserts.gltf [1.36MB] > C:\Users\psree\Downloads\desserts\desserts-transformed.glb [466.87KB] (66%)
Author: Cookies and Cream (https://sketchfab.com/modelsbyheart)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/desserts-e18c3a976b8b474fb5648d7012163f52
Title: desserts
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/desserts-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials["Material.013"]}
        position={[-0.401, 0.512, 1.054]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.676}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials["Material.015"]}
        position={[-0.401, 0.512, 1.054]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.676}
      />
      <mesh
        geometry={nodes.Object_9.geometry}
        material={materials["Material.014"]}
        position={[-0.401, 0.512, 1.054]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.676}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials["Material.016"]}
        position={[-0.078, 0.001, 1.116]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={10.414}
      />
      <mesh
        geometry={nodes.Object_17.geometry}
        material={materials["Material.011"]}
        position={[-0.401, 0.492, 1.054]}
        rotation={[-0.683, 0.681, 1.022]}
        scale={0.417}
      />
      <mesh
        geometry={nodes.Object_19.geometry}
        material={materials["Material.012"]}
        position={[-0.401, 0.492, 1.054]}
        rotation={[-0.683, 0.681, 1.022]}
        scale={0.417}
      />
      <mesh
        geometry={nodes.Object_23.geometry}
        material={materials["Material.010"]}
        position={[-0.401, 0.492, 1.054]}
        rotation={[-0.683, 0.681, 1.022]}
        scale={0.417}
      />
      <mesh
        geometry={nodes.Object_28.geometry}
        material={materials["Material.004"]}
        position={[-0.525, 0.638, -1.187]}
        rotation={[1.547, 0.054, 0.694]}
        scale={0.457}
      />
      <mesh
        geometry={nodes.Object_30.geometry}
        material={materials["Material.001"]}
        position={[-0.527, 0.62, -1.257]}
        rotation={[Math.PI / 2, 0, 0.869]}
        scale={0.508}
      />
      <mesh
        geometry={nodes.Object_32.geometry}
        material={materials["Material.003"]}
        position={[-0.637, 0.62, -0.934]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.508}
      />
      <mesh
        geometry={nodes.Object_38.geometry}
        material={materials["Material.005"]}
        position={[-0.637, 0.62, -0.934]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.508}
      />
    </group>
  );
}

useGLTF.preload("/models/desserts-transformed.glb");
