/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 dice.gltf --transform 
Files: dice.gltf [56.72KB] > C:\Users\psree\Downloads\dice\dice-transformed.glb [44.39KB] (22%)
Author: Maxwell Walton (https://sketchfab.com/MaxwellWalton)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dice-bbb7c5a19a2d4cedab4661b3f705a814
Title: Dice
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/dice-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.blinn1SG}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_3.geometry}
        material={materials.blinn2SG}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/dice-transformed.glb");
